package consts

const (
	MODULE_NAME_AGE                  string = "AgeModule"
	MODULE_NAME_AUDIO                string = "AudioModule"
	MODULE_NAME_LENGTH               string = "LengthModule"
	MODULE_NAME_LOGMATCH             string = "LogMatchModule"
	MODULE_NAME_MAXSIZE              string = "MaxSizeModule"
	MODULE_NAME_RESOLUTION           string = "ResolutionModule"
	MODULE_NAME_SIZEAPPROX           string = "SizeApproxModule"
	MODULE_NAME_LEGACY               string = "LegacyModule"
	MODULE_NAME_ERRORSKIP            string = "ErrorSkipModule"
	MODULE_NAME_ERRORREPLACE         string = "ErrorReplaceModule"
	MODULE_NAME_DUPLICATELENGTHCHECK string = "DuplicateLengthCheckModule"
	MODULE_FLAG_SKIP                 string = "AllowReplacement"
	AUDIO_ACC_LOW                    string = "low"
	AUDIO_ACC_MED                    string = "med"
	AUDIO_ACC_HIGH                   string = "high"
	LOGMATCH_MODE_INCLUDE            string = "include"
	LOGMATCH_MODE_NEUTRAL            string = "neutral"
	LOGMATCH_MODE_EXCLUDE            string = "exclude"
	RESUME                           string = "resume signal"
	OBSOLETE_DIR                     string = ".obsolete"
	DONE_DIR                         string = "done"
	EXIST_DIR                        string = "exists"
	COMPAT_CPARAM_PREFIX             string = "PI"
	INSERT                           string = "insert"
	UPDATE                           string = "update"
	DELETE                           string = "delete"
	GET                              string = "GE"
)
