name: Go

on:
  release:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Target Custom Tag'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.18
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: windows
        goarch: amd64
        binary_name: avior-go
